first_name=input("Please enter your first name: ")
middle_initial=input("Please enter your middle initial: ")
last_name=input("Please enter your last name: ")
street_address=input("Please enter your street address: ")
city=input("please enter your city: ")
state_abbreviation=input("please enter your state abbreviation: ")
zip_code=input("Please enter your zip code:")
phone_number=input("Please enter your phone number: ")
email_address=input("Please enter your email address: ")
print(f"Hello,{first_name} {middle_initial} {last_name}!")
